# ----------- CONFIGURABLE START -----------
title:            "Pawu Blog"
description:      "Yet another unnecessary blog"
url:              https://pawelkondraciuk.github.io # Site url, without a slash at the end.
signoff:          "Pawu" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: "UA-96526260-1" # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Blog
    url:          /
    external:     false
  - name:         O mnie
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
